//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excercise
    {
        public Excercise()
        {
            this.Muscles = new HashSet<Muscle>();
            this.ProgramExcercises = new HashSet<ProgramExcercise>();
            this.Statistics = new HashSet<Statistic>();
        }
    
        public int ExcerciseId { get; set; }
        public string Name { get; set; }
        public string Complexity { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Muscle> Muscles { get; set; }
        public virtual ICollection<ProgramExcercise> ProgramExcercises { get; set; }
        public virtual ICollection<Statistic> Statistics { get; set; }
    }
}
