//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramExcercise
    {
        public System.Guid ProgramExcerciseId { get; set; }
        public string Day { get; set; }
        public short Order { get; set; }
        public string SetCounts { get; set; }
        public string RepsScheme { get; set; }
        public System.Guid ProgramProgramId { get; set; }
    
        public virtual Excercise Excercise { get; set; }
        public virtual Program Program { get; set; }
    }
}
