//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Trainings = new HashSet<Training>();
            this.ProgramExcercises = new HashSet<ProgramExcercise>();
        }
    
        public int ProgramId { get; set; }
        public int UserUserId { get; set; }
        public string Name { get; set; }
        public bool IsOpenToWorld { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Author { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
        public virtual ICollection<ProgramExcercise> ProgramExcercises { get; set; }
    }
}
