//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTracker.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BodyStamps = new HashSet<BodyStamp>();
            this.Friends = new HashSet<User>();
            this.Programs = new HashSet<Program>();
            this.Tweets = new HashSet<Tweet>();
            this.Trainings = new HashSet<Training>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<BodyStamp> BodyStamps { get; set; }
        public virtual ICollection<User> Friends { get; set; }
        public virtual ICollection<Program> Programs { get; set; }
        public virtual ICollection<Tweet> Tweets { get; set; }
        public virtual ICollection<Training> Trainings { get; set; }
    }
}
